jobs: 
- name: kubernetes-push
  public: true
  plan:
  - get: git
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: devth/helm
          tag: '2.7.2'
      inputs: 
        - name: git
      outputs: 
        - name: chart
      run:
        path: sh
        args:
        - -exc
        - |
          cd git
          helm package .
          mv myapp-0.1.0.tgz ../chart
  - put: kubernetes
    params:
      chart: chart/myapp-0.1.0.tgz     
    
resources: 
- name: git
  type: git
  source:
    uri: https://github.com/Sharor/kubernetes-resource.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: kubernetes
  type: helm
  source:
    cluster_url: https://192.168.99.100:8443
    cluster_ca: {{minikube_cert_base64}}    
    admin_cert: {{minikube_admin_crt_base64}}
    admin_key: {{minikube_admin_key_base64}}

resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource