jobs: 
- name: kubernetes-push
  public: true
  plan:
  - get: git
    trigger: true
  - get: kubernetes
  - put: kubernetes
    params:
      file: git/deployment.yml      
    
resources: 
- name: git
  type: git
  source:
    uri: https://github.com/Sharor/kubernetes-resource.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: kubernetes
  type: kubernetes
  source:
    cluster_url: https://192.168.99.100:8443
    certificate_authority: {{minikube_cert}}
    client_certificate: {{minikube_admin}}
    client_key: {{minikube_key}}
   

resource_types: 
- name: kubernetes
  type: docker-image
  source:
    repository: sharor/kubernetes-resource
    tag: '1.0.30'