jobs: 
- name: test-pull-request
  public: true
  plan:
  - get: github-pull-request
    trigger: true
    version: every
  - task: test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: golang
          tag: "1.9"
      inputs: 
        - name: git
        - name: github-pull-request
      outputs: 
        - name: artifacts
      run:
        path: sh
        args:
        - -exc
        - |
            cd github-pull-request 
            C_PATH=$(pwd)
            go test -v -p 1 ./...
    on_success:
      put: github-pull-request
      params:
        path: github-pull-request
        status: success
    on_failure:
      put: github-pull-request
      params:
        path: github-pull-request
        status: failure
  - put: github-pull-request
    params:
      path: github-pull-request
      status: success
      merge:
        method: merge
        commit_msg: github-pull-request/pipeline/commitmsg.md
    
- name: build
  public: true
  plan: 
  - get: git
    trigger: true
  #- get: github-pull-request
  #  passed: [test-pull-request]
  - get: version
  - put: version
    params: {bump: patch}
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: golang
          tag: "1.9"
      inputs: 
        - name: git
      outputs: 
        - name: artifacts
      run:
        path: sh
        args:
        - -exc
        - |
            C_PATH=$(pwd)
            cd git           
            export GOOS=linux
            export GOARCH=amd64
            export CGO_ENABLED=0
            go build -a -installsuffix cgo -o $C_PATH/artifacts/check check/check.go
            go build -a -installsuffix cgo -o $C_PATH/artifacts/in in/in.go 
            go build -a -installsuffix cgo -o $C_PATH/artifacts/out out/out.go 

            chmod +x $C_PATH/artifacts/check
            chmod +x $C_PATH/artifacts/in
            chmod +x $C_PATH/artifacts/out
            cp Dockerfile $C_PATH/artifacts/Dockerfile
            
  - put: release
    params:       
      build: artifacts
      cache: false
      tag: version/version
      tag_as_latest: true

resources: 
- name: github-pull-request
  type: pull-request
  source:
    access_token: {{concourse-pull-request-token}}
    private_key: {{concourse-token}}
    repo: Sharor/kubernetes-resource
    base: master

- name: git
  type: git
  source:
    uri: https://github.com/Sharor/kubernetes-resource.git
    branch: master
    username: {{github-username}}
    password: {{github-password}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.0
    uri: git@github.com:Sharor/kubernetes-resource.git
    branch: version
    file: version
    private_key: {{concourse-token}}

- name: release
  type: docker-image
  source:
    repository: sharor/kubernetes-resource
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

resource_types: 
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
    tag: v31